# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1458d018a29dabb7026b9a77a14be67a4dca20c442b99d9f753829dde6c9e0edd201cf7a57744a1520a934cb4a85b849541031d5fc8b36aa43776ebb48d47b45

test:
  secret_key_base: f6da290e1f7b3ef5deb684eabdd04f2de9dd2b251d398bb753d452039b29bdfec814acd23c627941761ada7fe2048e279c2c31ae2829a3304319f460724f802a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
